spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

integrations:
  exchange-rates:
    url: https://api.exchangeratesapi.io/v1/
    api-key: ${EXCHANGE_RATES_API_KEY}
    endpoints:
      convert: /convert