spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/myfinance}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

integrations:
  exchange-rates:
    url: https://api.exchangeratesapi.io/v1/
    api-key: ${EXCHANGE_RATES_API_KEY:your_api_key}
    endpoints:
      convert: /convert