name: Build and Test

on:
  workflow_call:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'

      - name: Verify Java Version
        run: java -version

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Project Dependencies
        run: mvn --batch-mode dependency:go-offline

      - name: Compile and Package
        run: mvn --batch-mode package

      - name: Run Tests
        run: mvn --batch-mode test